# Generated by Django 4.0.5 on 2022-06-23 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('month_price', models.IntegerField()),
                ('year_price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
