# Generated by Django 4.0.5 on 2022-06-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='max_capacity',
            new_name='max_employees_qty',
        ),
    ]
