# Generated by Django 4.0.5 on 2022-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_rename_max_capacity_tariff_max_employees_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_one_price', models.PositiveIntegerField()),
                ('test_three_price', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
