# Generated by Django 2.2.4 on 2021-10-21 09:33

from django.db import migrations

from tariffs.models import TestPrice


def change_location(apps, schema_editor):
    TestPrice.objects.create(
        test_one_price=30000,
        test_three_price=30000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0004_testprice'),
    ]

    operations = [
        migrations.RunPython(change_location),
    ]
