# Generated by Django 4.0.5 on 2022-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_score_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='reason',
        ),
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='points',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
