# Generated by Django 4.0.5 on 2022-09-13 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_alter_score_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
