# Generated by Django 4.0.5 on 2023-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_alter_reason_score_alter_score_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='name_kz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
