# Generated by Django 4.0.5 on 2023-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_score_name_en_score_name_kz_score_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='score',
            name='name_kz',
        ),
        migrations.RemoveField(
            model_name='score',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='reason',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reason',
            name='name_kz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reason',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
