# Generated by Django 4.0.5 on 2023-03-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_remove_score_name_en_remove_score_name_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reason',
            old_name='name_kz',
            new_name='name_kk',
        ),
    ]
