# Generated by Django 4.0.5 on 2022-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationToCreateCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('company_name', models.CharField(max_length=200)),
                ('company_legal_name', models.CharField(blank=True, max_length=200)),
                ('employees_qty', models.IntegerField(default=0)),
                ('years_of_work', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Declined')], default=1)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
