# Generated by Django 4.0.5 on 2022-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicationtocreatecompany_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtocreatecompany',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
