# Generated by Django 4.0.5 on 2022-06-15 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationtocreatecompany_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtocreatecompany',
            name='employees_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='applicationtocreatecompany',
            name='years_of_work',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
