# Generated by Django 4.0.5 on 2022-06-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_testapplication_tariffapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffapplication',
            old_name='user',
            new_name='owner',
        ),
    ]
