# Generated by Django 4.0.5 on 2022-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_rename_user_tariffapplication_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tariffapplication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
