# Generated by Django 4.0.5 on 2022-06-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_is_active'),
        ('applications', '0008_tariffapplication_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffapplication',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tariffs.tariff'),
        ),
    ]
