# Generated by Django 4.0.5 on 2022-06-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_tariffapplication_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtocreatecompany',
            old_name='employees_qty',
            new_name='max_employees_qty',
        ),
    ]
