# Generated by Django 4.0.5 on 2022-08-03 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_rename_employees_qty_applicationtocreatecompany_max_employees_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtocreatecompany',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (2, 'Yearly')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationtocreatecompany',
            name='tariff_id',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariffapplication',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (2, 'Yearly')], default=1),
            preserve_default=False,
        ),
    ]
