# Generated by Django 4.0.5 on 2022-08-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_alter_company_owner'),
        ('applications', '0012_applicationtocreatecompany_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testapplication',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='testapplication',
            old_name='test',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='testapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='testapplication',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_applications', to='companies.company'),
        ),
        migrations.AddField(
            model_name='testapplication',
            name='test_type',
            field=models.IntegerField(choices=[(1, '1. Heart PRO'), (2, '2. Brain'), (3, '3. Brain PRO'), (4, '4. Heart')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Declined'), (4, 'Used')], default=1),
        ),
    ]
