# Generated by Django 4.0.5 on 2022-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_testapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapplication',
            name='used_quantity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
