# Generated by Django 4.0.5 on 2022-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_testapplication_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffapplication',
            name='is_instant_apply',
            field=models.BooleanField(default=False),
        ),
    ]
