# Generated by Django 4.0.5 on 2022-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_tariffapplication_is_instant_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtocreatecompany',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Declined'), (4, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='tariffapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Declined'), (4, 'Canceled')], default=1),
        ),
    ]
