# Generated by Django 4.0.5 on 2023-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_applicationtocreatecompany_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtocreatecompany',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
