# Generated by Django 4.0.5 on 2022-06-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assistant_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Marketing-sales'), (2, 'Production workers')], null=True),
        ),
    ]
