# Generated by Django 4.0.5 on 2022-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_user_assistant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assistant_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Marketing-sales'), (2, 'Production workers')], null=True),
        ),
    ]
