# Generated by Django 4.0.5 on 2023-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_acceptcode_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_new',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
