# Generated by Django 4.0.5 on 2023-04-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
