# Generated by Django 4.0.5 on 2022-06-21 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('comment', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='timesheet/')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'On time'), (2, 'Late'), (3, 'Absent'), (4, 'On vacation')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timesheet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
