# Generated by Django 4.0.5 on 2022-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_alter_departmentschedule_week_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeschedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'week_day'), name='unique schedule in company for user'),
        ),
    ]
