# Generated by Django 4.0.5 on 2022-06-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_employeeschedule_unique_together_and_more'),
        ('timesheet', '0004_alter_employeeschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
    ]
