# Generated by Django 4.0.5 on 2022-06-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_alter_timesheet_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
