# Generated by Django 4.0.5 on 2022-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_alter_timesheet_check_out'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'day'), name='unique timesheet in company for user'),
        ),
    ]
