# Generated by Django 4.0.5 on 2022-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_timesheet_unique timesheet in company for user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
