# Generated by Django 4.0.5 on 2022-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_alter_timesheet_check_in_alter_timesheet_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
