# Generated by Django 4.0.5 on 2022-07-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_remove_role_unique company-user_and_more'),
        ('timesheet', '0013_alter_departmentschedule_week_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeschedule',
            name='unique schedule in company for user',
        ),
        migrations.RemoveConstraint(
            model_name='timesheet',
            name='unique timesheet in company for user',
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='company',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='companies.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timesheet', to='companies.role'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.UniqueConstraint(fields=('role', 'week_day'), name='unique schedule'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('role', 'day'), name='unique timesheet'),
        ),
    ]
