# Generated by Django 4.0.5 on 2022-07-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_remove_role_unique company-user_and_more'),
        ('timesheet', '0014_remove_employeeschedule_unique schedule in company for user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='companies.role'),
        ),
    ]
