# Generated by Django 4.0.5 on 2022-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_alter_timesheet_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={'ordering': ('week_day',)},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('day',)},
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'On time'), (2, 'Late'), (3, 'Absent'), (4, 'On vacation'), (5, 'Day off'), (6, 'Future day')], default=1),
        ),
    ]
