# Generated by Django 4.0.5 on 2022-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0017_timesheet_debug_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
