# Generated by Django 4.0.5 on 2022-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0018_alter_timesheet_time_from_alter_timesheet_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timezone',
            field=models.CharField(default='+06:00', max_length=10),
        ),
    ]
