# Generated by Django 4.0.5 on 2022-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0019_timesheet_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentschedule',
            name='timezone',
            field=models.CharField(default='+06:00', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='timezone',
            field=models.CharField(default='+06:00', max_length=10),
        ),
    ]
