# Generated by Django 4.0.5 on 2022-12-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0020_departmentschedule_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentschedule',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='timezone',
        ),
    ]
