# Generated by Django 4.0.5 on 2023-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0021_remove_departmentschedule_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='check_in_new',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='check_out_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
    ]
