# Generated by Django 4.0.5 on 2023-04-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0022_employeeschedule_is_night_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'On time'), (2, 'Late'), (3, 'Absent'), (4, 'On vacation'), (5, 'Day off'), (6, 'Future day'), (7, 'Take off')], default=1),
        ),
    ]
