# Generated by Django 4.0.5 on 2023-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0022_employeeschedule_is_night_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='check_in_new',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='check_out_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
