# Generated by Django 4.0.5 on 2023-03-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('android_version', models.CharField(max_length=250)),
                ('ios_version', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
