# Generated by Django 4.0.5 on 2022-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='department',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
    ]
