# Generated by Django 4.0.5 on 2022-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_rename_schedule_departmentschedule_employeeschedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'role', 'user'), name='unique role in company for user'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('department', 'role', 'user'), name='unique role in department for user'),
        ),
    ]
