# Generated by Django 4.0.5 on 2022-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_employeeschedule_user_alter_role_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'HR'), (3, 'Observer'), (4, 'Employee')], default=4),
        ),
    ]
