# Generated by Django 4.0.5 on 2022-06-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
