# Generated by Django 4.0.5 on 2022-06-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_employeeschedule_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='radius',
            field=models.IntegerField(default=50),
        ),
    ]
