# Generated by Django 4.0.5 on 2022-06-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_department_radius'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='user',
        ),
        migrations.DeleteModel(
            name='DepartmentSchedule',
        ),
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
