# Generated by Django 4.0.5 on 2022-06-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_employeeschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
