# Generated by Django 4.0.5 on 2022-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_remove_company_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique role in company for user',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique role in department for user',
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique role in company for user'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('department', 'user'), name='unique role in department for user'),
        ),
    ]
