# Generated by Django 4.0.5 on 2022-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_remove_role_unique role in company for user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique role in company for user',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique role in department for user',
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique company-user'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('department', 'user'), name='unique department-user'),
        ),
    ]
