# Generated by Django 4.0.5 on 2022-06-24 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_employees_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
