# Generated by Django 4.0.5 on 2022-06-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_alter_department_head_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.department'),
        ),
    ]
