# Generated by Django 4.0.5 on 2022-06-29 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_alter_department_head_of_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('time_tracking_enabled', models.BooleanField(default=True)),
                ('tests_enabled', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
