# Generated by Django 4.0.5 on 2022-06-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_alter_role_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.company'),
        ),
    ]
