# Generated by Django 4.0.5 on 2022-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_alter_role_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(1, 'HR'), (2, 'Observer'), (3, 'Employee'), (4, 'Head of department')], default=3),
        ),
    ]
