# Generated by Django 4.0.5 on 2022-06-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_companyservice'),
        ('companies', '0026_alter_role_role'),
    ]

    operations = [
    ]
