# Generated by Django 4.0.5 on 2022-07-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-created_at',)},
        ),
    ]
