# Generated by Django 4.0.5 on 2022-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_alter_role_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique company-user',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique department-user',
        ),
    ]
