# Generated by Django 4.0.5 on 2022-07-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_alter_company_options_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
