# Generated by Django 2.2.4 on 2021-10-21 09:33

from django.db import migrations

from companies.models import Department


def change_location(apps, schema_editor):
    Department.objects.update(head_of_department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_alter_company_owner'),
    ]

    operations = [
        migrations.RunPython(change_location),
    ]
