# Generated by Django 4.0.5 on 2022-12-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_department_is_manual_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='timezone',
            field=models.CharField(default='+06:00', max_length=10),
        ),
    ]
