# Generated by Django 4.0.5 on 2022-12-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_department_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
