# Generated by Django 4.0.5 on 2023-03-03 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0039_company_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=22, validators=[django.core.validators.MinValueValidator(0)])),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=22, validators=[django.core.validators.MinValueValidator(0)])),
                ('radius', models.IntegerField()),
                ('employees', models.ManyToManyField(blank=True, related_name='zones', to='companies.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
