# Generated by Django 4.0.5 on 2023-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='in_zone',
            field=models.BooleanField(default=True),
        ),
    ]
