# Generated by Django 4.0.5 on 2023-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_role_in_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='checkout_any_time',
            field=models.BooleanField(default=True),
        ),
    ]
