# Generated by Django 4.0.5 on 2023-04-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_role_checkout_any_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='start_inaccuracy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
