# Generated by Django 4.0.5 on 2022-06-17 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0009_role_unique role in company for user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('statistic_type', models.IntegerField(choices=[(1, 'General statistics'), (2, 'Double statistics')], default=1)),
                ('plan', models.IntegerField(blank=True, null=True)),
                ('visibility', models.IntegerField(choices=[(1, 'Open to everyone'), (2, 'Open by department'), (3, 'Hidden'), (4, 'Employees')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='companies.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='companies.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='bepro_statistics.statistic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observing_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
