# Generated by Django 4.0.5 on 2022-06-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepro_statistics', '0003_alter_statistic_statistic_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistic',
            old_name='weekday',
            new_name='day',
        ),
    ]
