# Generated by Django 4.0.5 on 2022-07-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_alter_company_owner'),
        ('bepro_statistics', '0006_alter_userstatistic_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statisticobserver',
            unique_together={('statistic', 'role')},
        ),
    ]
