# Generated by Django 4.0.5 on 2022-10-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepro_statistics', '0009_alter_statistic_plan_alter_userstatistic_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='plan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='fact',
            field=models.FloatField(),
        ),
    ]
