# Generated by Django 4.0.5 on 2022-08-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0034_alter_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_type', models.IntegerField(choices=[(1, '1. Heart PRO'), (2, '2. Brain'), (3, '3. Brain PRO'), (4, '4. Heart')])),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('is_man', models.BooleanField()),
                ('finished_at', models.DateField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Await'), (2, 'Finished')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='companies.company')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
