# Generated by Django 4.0.5 on 2022-08-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_alter_company_owner'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_man',
        ),
        migrations.RemoveField(
            model_name='test',
            name='role',
        ),
        migrations.AddField(
            model_name='test',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='test',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='test',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='test',
            name='version',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='test',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
