# Generated by Django 4.0.5 on 2022-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_options_remove_test_is_man_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
