# Generated by Django 4.0.5 on 2023-04-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0041_role_in_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_notified', models.BooleanField(default=False)),
                ('check_out_notified', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
