# Generated by Django 4.0.5 on 2023-05-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
